# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  instance_tag: chess-online
  name: chess-online

env_variables:
  test: "test"
