# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
runtime: nodejs
env: flex
entrypoint: cd client && yarn build:prod && cd ../server && yarn start

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  instance_tag: scott2vpc
  name: scott2vpc

env_variables:
  PORT: "8989"
